name: Build

on:
  push:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@main

    - name: Get NDK
      run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip >> /dev/null

    - name: Unzip libraries
      run: |
          cd android/libraries
          unzip libs.zip

    - name: Build GLOVE lib
      run: |
          $ANDROID_NDK_LATEST_HOME/ndk-build \
          APP_BUILD_SCRIPT=./android/jni/Android_glove.mk \
          NDK_APPLICATION_MK=./android/jni/Application.mk \
          NDK_PROJECT_PATH=./android \
          TARGET_OUT=./android/obj/build/glove

    - name: Build APP
      run: |
          $ANDROID_NDK_LATEST_HOME/ndk-build \
          APP_BUILD_SCRIPT=./android/jni/Android_app.mk \
          NDK_APPLICATION_MK=./android/jni/Application.mk \
          NDK_PROJECT_PATH=./android \
          TARGET_OUT=./android/obj/build

    - name: Upload build output
      uses: actions/upload-artifact@main
      with:
        name: GLOVE
        path: android/obj/build
